### ISSUE TITLE
Docs metadata incorrect?

### ISSUE THREAD

**Issue by maartenkling** [mollie/mollie-api-python#155]
https://github.com/mollie/mollie-api-python/blob/b20b637b49caccbb55f99229361f679acc56c2bd/examples/02-webhook-verification.py#L33

Incorrect:
ipdb> payment.metadata
*** AttributeError: 'Payment' object has no attribute 'metadata'

Works:
ipdb> payment['metadata']
{u'my_webshop_id': u'1583922181'}

**Comment by whyscream** [comment]
The examples are for the v2 code. The `metadata` property on a `Payment` object has been part of the mollie client since v2.0.0.

You are probably using a 1.x.x version of the client. Feel free to upgrade your mollie client, or take a look at the old documentation: https://github.com/mollie/mollie-api-python/tree/v1-develop/examples

**Comment by maartenkling** [comment]
Used old software, unrelated to this example.
