### ISSUE TITLE
Refund seems not working: Error executing API call (request): Unsupported input received.

### ISSUE THREAD

**Issue by piqoni** [mollie/mollie-api-python#33]
I'm doing a full refund in test mode following the example at README.md. My code:
```python
import Mollie

mollie = Mollie.API.Client()
mollie.setApiKey('test_****************************************')

payment = mollie.payments.get('tr_rW***********') # passing here the payment id in status paid
refund = mollie.payments.refund(payment)
```

Error is:
```
Traceback (most recent call last):
  File "/home/user/Desktop/Mollietest/refund_mollie.py", line 8, in <module>
    refund = mollie.payments.refund(payment)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Payments.py", line 23, in refund
    return self.refunds(payment).create(data)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 54, in create
    return self.rest_create(data)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 27, in rest_create
    result = self.performApiCall(self.REST_CREATE, path, data, params)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 82, in performApiCall
    raise error
Mollie.API.Error.Error: Error executing API call (request): Unsupported input received.
```

**Comment by mvdpanne** [comment]
Hey Edi,

Thank you for notifying us of your problem. I have run the exact same script, though with valid a API key and payment id of course, and unfortunately I see no problems on my side. When a valid payment id is provided, the payment is successfully being refunded, and returns a `refund` object. If the payment is already refunded, an error is returned indicating that.

Since your script fails on the last line, it means that the `payment` object has been retrieved successfully. I would very much appreciate it if you could share the contents of the `payment` object, such that we can investigate this problem further.

Please make sure any personal/sensitive data is redacted or in some way anonymized.

**Comment by piqoni** [comment]
Hey Maikel, 

Thanks for the swift response. 

payment object (I put stars on sensitive data):
```
{u'status': u'paid', u'description': u'Order 485672', u'countryCode': u'UA', u'createdDatetime': u'2018-01-25T13:48:54.0Z', u'mode': u'test', u'amountRefunded': u'0.00', u'id': u'tr_u********', u'issuer': u'ideal_TESTNL99', u'resource': u'payment', u'links': {u'redirectUrl': u'http://a4338bf6.ngrok.io/mycallbackroute&order_id=485672', u'webhookUrl': u'http://a4338bf6.ngrok.io/mywebhookroute'}, u'amountRemaining': u'36.40', u'locale': u'en', u'amount': u'11.40', u'paidDatetime': u'2018-01-25T13:49:07.0Z', u'profileId': u'pfl_xJ*******', u'metadata': {u'order_id': u'485672'}, u'method': u'ideal', u'details': {u'consumerName': u'T. TEST', u'consumerAccount': u'***********************', u'consumerBic': u'TESTNL99'}}
```

**Comment by mvdpanne** [comment]
Hey Edi,

Good news. I actually forgot to switch back to the `master` branch yesterday and was thus testing on the yet to be merged `refunds-and-chargeback-support` branch. I now tested your script on the master branch, and it fails there.

So, when that PR is merged, your problem should also be fixed.
